name: SFDX-CLI Deploy from repository
on: 
  push:
    branches:
      - main

jobs:
  create-scratch-org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git hub Code
        uses: actions/checkout@v3
      - name: Install SFDX
        run: |
             echo "Sfdx version and installation"
             npm install @salesforce/cli --global
             sf --version
      - run: echo "${{secrets.SALESFORCE_SECRET_KEY}}"  > server.key
      - run: sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY}} --jwt-key-file=server.key --username=${{secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername
      - name: Create Scrtach Org
        run: sf org create scratch --definition-file config/project-scratch-def.json --no-namespace --duration-days 30
