name: SFDX-CLI Deploy from repository
on: 
  push:
    branches:
      - master

jobs:
  create-scratch-org:
    environment: PROD
    env:
      consumer_key: ${{secrets.SALESFORCE_CONSUMER_KEY}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git hub Code
        uses: actions/checkout@v3
      - name: Install SFDX
        run: |
             echo "Sfdx version and installation"
             npm install @salesforce/cli --global
             sf --version
      - run: echo "${{secrets.SALESFORCE_SECRET_KEY}}"  > server.key
      - run: sfdx force:auth:jwt:grant --client-id=$consumer_key --jwt-key-file=server.key --username=${{secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername
      - run: echo "Create Scrtach Org"
