name: SFDX-CLI Deploy from repository
on: [push]
jobs:
  SFDX-CLI-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Github Action running on ${{runner.os}}"
      - run: echo "Retrieving ${{github.ref}} from ${{github.repository}}"
      - uses: Action/checkout@v2
      - run: npm install SFDX-CLI -g
      - run: echo "${{secrets.SALESFORCE_SECRET_KEY}}"  > server.key
      - run: sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY}} --jwt-key-file=server.key --username=${{secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername
      - run: sfdx force:source:deploy --manifest=manifest/package.xml